### ISSUE TITLE
유저 정보를 리덕스에 저장 (`/me` 요청 최적화)

### ISSUE THREAD

**Issue by humonnom** [Mapps-unit/frontend#122]
- 코드위치: Login.js
- `/me`에서 가져온 유저 데이터를 리덕스에 저장

**Comment by echoja** [comment]
리덕스의 유저 상태는 총 **세가지**.
- 초기화상태 (뭔가 해야 하는 상태) (initial)
- 유저정보가 없음. (no_user)
- 유저정보가 있음. (yes_user)

이렇게 구성하는 목적: **`/me` 요청을 여러 번 하지 않게 하기 위해서.**

- useUser(...) 를 호출하여 일반 컴포넌트에서 현재 로그인한 유저의 정보를 가져오자! 그런데, 유저 정보가 없으면 null임.
- useUser 에는 리덕스의 user 정보를 바라보고 있음.
- 만약 user정보가 initial 이라면 `/me` 로 요청 시도.
- 만약 user정보가 no_user 라면 null 리턴
- 만약 user 정보가 있으면 그걸 리턴.

리덕스 user 정보를 갱신시켜줘야 할 때

- useRequestAuth 에서 만약 refreshToken 까지 만료되서 로그아웃 되어야 하는 상황이라면, 리덕스의 user 정보도 no_user 로 바꿔야 함.
- 로그인/회원가입을 하게 되면 리덕스에 유저 정보를 넣어서 yes_user 상태로 만들어야 함.
- 로그아웃 할 때에도 no_user로 바꿔야 함.
