### ISSUE TITLE
로그인 & 회원가입 리서치

### ISSUE THREAD

**Issue by echoja** [Mapps-unit/frontend#53]
## 기본 프로세스
- 일단 결정해야 할 게 있을때, **고민하지 말고 다른 사람들이 어떻게 했는지 검색** (2~3개)
- 그 다음 러프하게 결정. 이 정도 느낌이면 문제 없겠다.
- 예: 로그인의 지속시간은 얼마나 해야 할까?? -> https://devtalk.kakao.com/t/access-token/792
- "이런 방향으로 가는 게 좋은 것 같다"라고 주장할 때 근거를 주루룩 쓰는 것보다 예시 & 한두 마디 정도면 충분할듯?
- 지금 여기 #53 이슈 아래에 코멘트로 조사 내용 작성

## 리서치 내용
- 페이지 구성 (약관 페이지와 회원가입 페이지를 나눌 수도 있고, 합칠 수도 있고, 페이지 별도 안두고 팝업으로 띄울 수도 있고..) -> 각 방법에 대해 어떨게 좋을지? 이유와 함께
- 회원가입 시 필요할 정보 (가장 기본적인 건 `이메일`과 `비밀번호`)
- 용어 정리해보기. (예) 이메일/비밀번호 회원가입 유저 -> **이메일유저**, 카카오 소셜 회원가입/로그인 유저 -> **카카오유저**)
- 여러 상황들을 구분하고, 우선순위 및 제외할 것 생각하기.
  - 카카오로 로그인한 사람이 이메일/비밀번호를 가지고 싶을 때
  - 이메일/비밀번호로 로그인한 사람이 카카오 연동하고 싶을 때
  - 이메일/비밀번호로 회원가입했던 사람이 추후 연동 없이 같은 이메일로 카카오로 로그인 시도했을 때
  - 비밀번호 변경을 하고 싶을 때
  - 카카오 연동한 사람이 로그아웃하고 다른 카카오 아이디로 로그인하고 싶을 때
  - 이미 로그인한 사람이 로그인 페이지 혹은 회원가입 페이지에 접근할 때
  - 카카오 연동한 사람이 카카오 탈퇴했을 때
  - 로그인 지속시간
  - 기타 등등..

위 기능들에 대해서 우선순위가 낮은 건 일단 대충 해놓고 마감기한 없는 별도 이슈로 분리가 가능
예: 회원가입 기능 만드는데 비밀번호 길이에 대한 강제 기능도 넣기는 해야겠는데, 일단 회원가입 기능이 더 중요하고 비밀번호 길이는 상대적으로 덜 중요함..
1. 회원가입 기능 만들고 이슈 만들고 작업 진행, 비밀번호 길이는 일단 제한이 없음.
2. 비밀번호 길이 제한두는 이슈를 만들어놓고 작업 미루기. (추후 일정 부여)

---

크리스마스 트리 회원가입할때 정도면 괜찮지 않을까?

**Comment by humonnom** [comment]
## 회원가입
중요도에 따라 1차, 2차로 나눔

#### 🚨 **Flow Chart**(1차)
회원가입부터 서비스 이용까지의 플로우차트가 필요함
* 연동 로그인 유저의 새로운 회원가입 시도
1. 연동 로그인 재시도(카카오 아이디 분실 등의 경우) -> 일단 보류
2. 자체 로그인 시도 -> 연동한 아이디가 있으므로 로그인으로 돌려주기

* 자체 로그인 유저의 새로운 회원가입 시도
1. 연동 회원가입 시도 -> 이미 가입된 회원임을 알려주고 로그인 페이지로 이동
2. 자체 회원가입 재시도 -> 이미 가입된 회원임을 띄우고 로그인 페이지로 이동

* 연동 로그인 회원과 자체 로그인 회원에 대한 정리 필요
1. 두 회원 사이에 권한 차이가 있는지 여부 -> 권한 같음
2. 추후 두 회원 사이의 연동이 필요한지 여부 -> 연동 필요하지 않다고 생각함(따로 관리)

* 비밀번호 변경시도(일단 보류)
1. 이미 로그인한 사람이 로그인 페이지 혹은 회원가입 페이지에 접근할 때
2. 연동 회원의 연동 서비스 탈퇴(예를 들면 카카오 탈퇴) -> 임시비밀번호를 재발급할 이메일을 받아놓거나 휴대폰 번호로 인증(g메일, 싸이월드가 그렇게 하고 있음) -> 일단은 아무 처리하지 않음

	![플레이넷 플로우차트](https://d2.naver.com/content/images/2015/06/helloworld-1188-4.png)

#### 🚨 사용자 용어정리(1차)

|용어|의미|권한|
|---|----|-----|
|유저(사용자)|onit 서비스 이용자||
|멤버(회원)|데이터 베이스에 있는 유저||
|연동로그인 회원|자체 로그인 회원|모든 서비스 이용 가능|
|자체로그인 회원|Oauth 로그인 회원|모든 서비스 이용 가능|
|비지터(방문자)|로그인 하지 않은 사용자|페이지 방문|
* 사용자의 지위에 따른 권한이 상세하게 정리될 필요가 있음


#### 🚨 사용자 시나리오(1차)
사용자가 온잇에서 제공하는 서비스를 이용하려면 아래와 같은 과정을 거쳐야 한다.

* 연동회원가입/자체회원가입 중 택1
* 연동회원가입시 카카오를 통한 회원가입이 이루어지고, 마지막 단계에서 이용약관동의
* 자체회원가입시 사용자가 정보를 채워넣는 과정이 이루어지고, 마지막 단계에서 이용약관동의

#### 🚨 비밀번호 제한사항(1차)
* ~~ 백엔드랑 보안 관련 이야기 필요할 듯 ~~
* ~~ 1차 배포에 포함되면 시급함 ~~
* 최소 7글자

#### 로그인 지속시간(2차)
* 백엔드랑 논의 필요
* 배포 전에만 정해지면 됨
* 자동 로그인 유지하는 것

#### 🚨 회원가입시 요구할 정보(1차)
* 이름
* URL(영문, 숫자, 대시-최소 4자, 최대 20자)
* 이메일
* 약관 복붙하기
* 분야선택
* 자체회원가입은 아이디, 비밀번호 필요

#### 이용약관(2차)
* 홍보를 위한 배포 전까지만 하면 될듯
---
#### 참고한 글
* [D2 - 플레이넷, 네이버 아이디로 게임을 할 수 있는 서비스](https://d2.naver.com/helloworld/1188)

* [D2 - Oauth1.0과 Oauth2.0](https://d2.naver.com/helloworld/24942)

**Comment by echoja** [comment]
회의록 참조: https://www.notion.so/heom/2021-12-29-dfe2973655b046d985ce38262d09b575

**Comment by echoja** [comment]
아직 더 리서치해야 한다고 함.

**Comment by humonnom** [comment]
수정 완료하였습니다.
