### ISSUE TITLE
자체 회원가입/로그인 기능 추가

### ISSUE THREAD

**Issue by humonnom** [Mapps-unit/frontend#70]
## 사전준비
- [x] 서버로 보낼 예시 JSON 파일 구상하기. 예: `{email: "eszqsc112@naver.com", password: "13241324", field: ["art", "..."], ...}` 제일 고된 이름짓기가 예상됨..

## 회원가입
- [x] 현재까지 진행된 것 본 리포지토리에 커밋, 리포지토리에 푸쉬
- [x] 디자인 입히기
- [x] 비밀번호 한번 쓸 건지, 두번 쓸 건지 관련 태킴과 상의

## 참조
- [기획 문서 (노션)](https://heom.notion.site/b12feab3f366466bb7f6a37c6e7d8e60)
- https://github.com/Mapps-unit/frontend/issues/53

**Comment by echoja** [comment]
아래 항목 다 된 다음에 진행

- #76 
- #73

**Comment by humonnom** [comment]
### 참고
|항목|허용|불허|최소|최대|중복체크|기타
|--|------|---|---|---|---|---|
|email||||||[validator](https://www.npmjs.com/package/validator) 라이브러리 isEmail()함수 사용|
|url|불허하는 문자 외 모든 문자 허용|underscore(_), trailing dot(:), space( )|필요
|nickname|모든 문자|1|15|필요
|password|영문,숫자,특수문자(한정적범위)|그 외 모든 문자||
|field|||1|n||

**Comment by echoja** [comment]
- 약관 부분은 다음으로 이동: #116
