### ISSUE TITLE
리팩토링

### ISSUE THREAD

**Issue by humonnom** [Mapps-unit/frontend#71]
#### 리팩토링 중에 공유할만한 수정사항 기록(타래)
   * 내용
      * 무엇을(before)
      * 어떻게 고쳤는지(after)
      * 고친 이유(설명) -> 자세한 내용은 커밋메세지로 적고 이슈에는 간단하게 작성
      * 커밋 링크달기

**Comment by humonnom** [comment]
#### Heom Juepark 미팅내용
##### 어떻게 리팩토링할까?
* [참고](https://usage.tistory.com/57?category=883489)

**Comment by echoja** [comment]
@Eomhyunjun @humonnom 본 이슈 어떻게 계속 운용할건지 체크해주세용

**Comment by echoja** [comment]
체크가 안되네요
