### ISSUE TITLE
위젯을 클릭하면 탭 복제가 되는 현상 해결

### ISSUE THREAD

**Issue by humonnom** [Mapps-unit/frontend#81]
normal 페이지에서 위젯을 클릭하면 `탭 복제` 가 되어 같은 탭이 하나 더 열립니다.

**Comment by Eomhyunjun** [comment]
ImageBox에서 링크 유무를 원래 null로 확인했었는데, 데이터셋이 바뀌면서 링크가 없음에도 url이 ""로 설정되었기 때문에 해당 조건문을 모두 통과하면서 생겨난 에러입니다. 해당 조건문 수정하여 해결하였습니다.

**Comment by Eomhyunjun** [comment]
#80 풀리퀘에서 해결되었습니다. (풀리퀘 만들고 메인에 머지 안된 상태에서, 개인레포에 푸쉬한 것들도 함께 머지되네요.)
