### ISSUE TITLE
위젯 편집 페이지에서 빈칸 Hover 및 클릭 기능 추가

### ISSUE THREAD

**Issue by echoja** [Mapps-unit/frontend#92]
- 큰 전체 레이아웃 컨테이너가 있고 그 안에 각각의 위젯 div 여러 개가 있음.
- 위젯 div 는 translate 로 좌표 계산이 됨. (absolute)

## Hover 기능

1. 큰 전체 레이아웃 mousemove event 받습니다. (addEventListener 또는 onMousemove 사용)
2. 그 이벤트가 가리키는 타겟이 컨테이너인지 체크합니다. (마우스가 배경 위에서 노는지, 위젯에서 노는지 체크)
3. 만약 배경 위에서 논다면, 좌표 계산해서 + 버튼 보여주기
4. 만약 위젯 위에서 논다면 + 버튼 안보여주기

**Comment by Eomhyunjun** [comment]
#102 에서 해결했습니다.
